# Generated by Django 4.0.3 on 2022-08-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image_alter_post_tags_alter_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='metadescription',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
