# Generated by Django 4.2 on 2023-06-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_category_description_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=10),
        ),
    ]
