# Generated by Django 4.2 on 2023-05-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catechism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=240)),
                ('text', models.TextField()),
                ('related', models.CharField(max_length=60)),
            ],
        ),
    ]
