# Generated by Django 4.0.3 on 2022-06-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(default='teste', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bible',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
