# Generated by Django 4.0.3 on 2022-06-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_books_slug_alter_bible_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(),
        ),
    ]
