# Generated by Django 4.0.3 on 2022-07-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_alter_books_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bible',
            old_name='book',
            new_name='book_id',
        ),
        migrations.AlterField(
            model_name='books',
            name='testament',
            field=models.CharField(max_length=2),
        ),
    ]
